default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host:

development:
  <<: *default
  database: friends_dev

test:
  <<: *default
  database: friends_test

production:
  <<: *default
  adapter: postgresql
  database: friends_prod